version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/fastifydb
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run build && node dist/index.js"

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
